In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [8]:
sigma_D = np.diag([3., 4., 5.])

In [36]:
w, U1 = np.linalg.eig(sigma_D)
print(w)
print(U1)

[3. 4. 5.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
ki = np.array([[0.,1.,0.]]).transpose()
kf = np.array([[1.,1.,1.]]).transpose()
kf /= np.linalg.norm(kf)

q = kf - ki
n = q / np.linalg.norm(q)

A = np.identity(3) + 2*n.dot(n.transpose())

new_sigma = A.dot(sigma_D).dot(A)

In [52]:
e1 = np.array([[1.,0.,0.]]).transpose()
e1 -= kf.transpose().dot(e1)*kf
e1 /= np.linalg.norm(e1)

e2 = np.array([[0.,0.,1.]]).transpose()
e2 -= kf.transpose().dot(e2)*kf
e2 /= np.linalg.norm(e2)

print(e1)
print(e2)

[[ 0.81649658]
 [-0.40824829]
 [-0.40824829]]
[[-0.40824829]
 [-0.40824829]
 [ 0.81649658]]


array([[-0.5]])

In [37]:
w, U2 = np.linalg.eig(new_sigma)
print(w)
print(U2)

[-4.44089210e-16  3.42264973e+00  4.57735027e+00]
[[-0.57735027 -0.78867513 -0.21132487]
 [-0.57735027  0.57735027 -0.57735027]
 [-0.57735027  0.21132487  0.78867513]]


In [27]:
print(kf.transpose().dot(U[:,0]))
print(kf.transpose().dot(U[:,1]))
print(kf.transpose().dot(U[:,2]))

[-1.]
[1.94289029e-16]
[-5.55111512e-17]


In [34]:
e1 = np.cross(ki[:,0], kf[:,0])
e1 /= np.linalg.norm(e1)

In [35]:
e1

array([ 0.70710678,  0.        , -0.70710678])

In [31]:
ki

array([[0.],
       [1.],
       [0.]])

In [38]:
U2.dot(U1.transpose())

array([[-0.57735027, -0.78867513, -0.21132487],
       [-0.57735027,  0.57735027, -0.57735027],
       [-0.57735027,  0.21132487,  0.78867513]])